### ISSUE TITLE
Implement Discord as Oauth2

### ISSUE THREAD

**Issue by JaviTrek** [JaviTrek/AW-Competitive#29]
So in order to save us a big headache with all the password saving, email verification, etc etc. We can make our users use Discord or some other social media (prefer Discord) to log in. We'd save their data and we wouldn't need to worry about making sure we don't have to create all the infrastructure for user verification.

**Comment by spopo003** [comment]
https://www.youtube.com/watch?v=qtVaNuTvY0c&list=PL_cUvD4qzbkwRMmqlviY0FXL54dEYRNbz

Love this tutorial

**Comment by JaviTrek** [comment]
> https://www.youtube.com/watch?v=qtVaNuTvY0c&list=PL_cUvD4qzbkwRMmqlviY0FXL54dEYRNbz
> 
> Love this tutorial

Yeah Anson the Developer is pretty good for learning. I really like that he doesn't take the easy route and actually explains stuff.
